# Spring Configuration
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${JWK_SET_URI}
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
          auth: true
    host: smtp.gmail.com
    username: productcatalogofficial@gmail.com
    password: ${EMAIL_PASSWORD}
    test-connection: true
    port: 587

server:
  servlet:
    context-path: /api/

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG