# Spring Configuration
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    username: c##guilherme
    password: passw0rd
    url: jdbc:oracle:thin:@//localhost:32118
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:32119/realms/product-catalog
          jwk-set-uri: http://localhost:32119/realms/product-catalog/protocol/openid-connect/certs
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
          auth: true
    host: smtp.gmail.com
    username: productcatalogofficial@gmail.com
    password: Produto123@
    test-connection: true
    port: 587


server:
  servlet:
    context-path: /api/

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG